# Sidebar navigation

- label: 'Home'
  link: '/'
- label: Pages
  items:
    - label: 'Cloud project'
      link: '/cloud_project'
    - label: 'Pub/Sub/Clone operations'
      link: '/pub_sub_clone_operations'
- label: Sites
  items:
    - label: Japan meteorological agency open data 1
      link: https://ap1.dag.iijgio.com/japan.meteorological.agency.1.site/iij1.japan.meteorological.agency.1.open.data.i.html
    - label: Japan meteorological agency open data 2
      link: https://ap2.dag.iijgio.com/japan.meteorological.agency.2.site/iij2.japan.meteorological.agency.2.open.data.i.html
    - label: monitor
      link: https://ap1.dag.iijgio.com/japan.meteorological.agency.1.site/monitor/meteorological_visualizer.html
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/public-tatsuya-noyori
