# Sidebar navigation

- label: 'Home'
  link: '/'
- label: Pages
  items:
    - label: 'Cloud project'
      link: '/cloud_project'
- label: Sites
  items:
    - label: AP Northeast 1
      link: https://s3.ap-northeast-1.wasabisys.com/japan.meteorological.agency.open.data.aws.js.s3.explorer/ap-northeast-1.html
    - label: US East 1
      link: https://s3.ap-northeast-1.wasabisys.com/japan.meteorological.agency.open.data.aws.js.s3.explorer/us-east-1.html
    - label: EU Central 1
      link: https://s3.ap-northeast-1.wasabisys.com/japan.meteorological.agency.open.data.aws.js.s3.explorer/eu-central-1.html
    - label: Monitor on cloud
      link: https://s3.ap-northeast-1.wasabisys.com/japan.meteorological.agency.open.data.aws.js.s3.explorer/org/meteorological_visualizer.html
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/public-tatsuya-noyori
